void moveDrive();
void elevate();
void intake_func();
void activteFlippers();
void activateIntake90();
void activateIntake180();
void activateElevation();
void rightFlyun(double percent);
void wheelsBrake();
void changeFlyPowerSecondController();