void moveDrive();
void elevate();
void intake_func();
void activateFlippers();
void activateIntake90();
void activateIntake180();
void activateIntake45();
void activateElevation();
void rightFlyun(double percent);
void wheelsBrake();