void route_skills(double start_heading);
void intake_in(int time);
void intake_out(int time);
void flywheel_in(int time);
void flywheel_out(int time);
void elevate_up(int time);
void elevate_down(int time);
void ez_skills_start_on_left();
void ez_skills_start_on_right();
void route_match_tanner();
void route_match_drew();
void shoot(int num);
void full_skills_route_part1();
void match_shoot_tanner();
void test_route();
void match_drew_MONEY();
